jobs:
  include:
    - stage: test
      script:
        - docker build --target all_tests -t test .
        - docker run --name todo-app-test --env DB_USER --env DB_PASS --env DB_NAME test
deploy:
  provider: script
  script: bash ci/deploy.sh
  on:
    branch: main
